[project]
name = "DLC-Clarity-Smart-Contract-Redstone"

[[project.requirements]]
contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[contracts.discreet-log-storage-v3]
path = "contracts/discreet-log-storage-v3.clar"
depends_on = []
