[project]
name = "DLC-Clarity-Smart-Contract-Redstone"

# [[project.requirements]]
# contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[contracts.dlc-manager-pricefeed-v1-01]
path = "contracts/dlc-manager-pricefeed.clar"
depends_on = []


##### Development contracts:

[contracts.redstone-verify]
path = "contracts/external/redstone-verify.clar"
depends_on = []

[contracts.dlc-create-callback-trait]
path = "contracts/dlc-create-callback-trait.clar"
depends_on = ["dlc-create-callback-trait"]

[contracts.protocol-contract]
path = "contracts/external/protocol-contract.clar"
depends_on = ["dlc-manager-pricefeed-v1-01", "dlc-create-callback-trait"]
